import Head from 'next/head'
import { Inter } from 'next/font/google'
import Sidebar from '../components/Sidebar'
import Center from '../components/Center'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-black h-screen overflow-hidden'>
      <Head>
        <title>Sppotify-Clone</title>
        <meta name="description" content="Generated by Spotify-clone" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Center />
      <Sidebar />
    </div>
  )
}
